# prometheus global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
rule_files:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9095']
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.178.65:8091',
                  '192.168.178.65:8092',
                  '192.168.178.65:8093',
                  '192.168.178.65:8094',
                  '192.168.178.65:8095',
                  '192.168.178.65:8096',
                  '192.168.178.65:8661',
                  '192.168.178.65:8662',
                  '192.168.178.65:8663']
